cc_library(
    name = "rrt_star",
    srcs = [
        "rrt_star.cpp",
    ],
    hdrs = [
        "rrt_star.hpp",
    ],
    deps = [
        "//modules/commons:commons",
        "//modules/world:world",
        "//modules/models/behavior:behavior",
        "//modules/models/dynamic:dynamic"
    ],
    visibility = ["//visibility:public"],
)
